spring.datasource.url=jdbc:postgresql://localhost:5432/gym_management
spring.datasource.username=postgres
spring.datasource.password=neshanth123@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true